# native-output — 지문 산출기 (fingerprint builder)
# data/corpus/<장르>/*.txt 를 형태소 분석해 장르별 문체 지문을 산출한다.
# 원칙: 지문의 모든 수치는 이 스크립트가 만든다(손수치 0). data/fingerprint/ 는 재생성 전용.
# holdout(data/holdout.md 에 등재된 파일)은 지문 계산에서 제외한다.
# 의존성: pip install kiwipiepy
# 실행: PYTHONIOENCODING=utf-8 python scripts/build-fingerprint.py
import json, re, sys, statistics
from pathlib import Path
from collections import Counter

try:
    from kiwipiepy import Kiwi
except ImportError:
    sys.exit("kiwipiepy 가 필요하다. 설치: pip install kiwipiepy")

DATA = Path(__file__).resolve().parent.parent / "data"
CORPUS = DATA / "corpus"
OUT = DATA / "fingerprint"
HOLDOUT_FILE = DATA / "holdout.md"

# AI 초안에 흔하지만 개인 코퍼스에는 없을 수 있는 상투 표현 후보 (never-use 판별용 탐침).
# 이 목록 자체는 수치가 아니라 탐침이며, 판별 결과(0회 여부)는 스크립트가 계산한다.
AI_TELL_PROBES = [
    "살펴보겠습니다", "알아보겠습니다", "살펴보도록 하겠습니다", "알아보도록 하겠습니다",
    "결론적으로", "종합적으로", "전반적으로", "궁극적으로", "본질적으로",
    "다양한 측면", "여러 측면", "중요한 역할을 합니다", "필수적인 요소",
    "라고 할 수 있습니다", "것으로 보입니다", "할 수 있을 것입니다",
    "주목할 만한", "흥미로운 점은", "명심해야 합니다", "잊지 마세요",
    "게임 체인저", "혁신적인", "획기적인", "놀라운",
    "먼저,", "둘째,", "셋째,", "마지막으로,",
    "에 대해 자세히", "를 통해 우리는", "함께 살펴보시죠",
]

HAPSYO = re.compile(r"(습니다|ᆸ니다|습니까|십시오)$")
HAEYO = re.compile(r"(어요|아요|에요|예요|죠|세요|네요|는데요|거든요)$")

def load_holdout():
    if not HOLDOUT_FILE.exists():
        return set()
    names = set()
    for line in HOLDOUT_FILE.read_text(encoding="utf-8").splitlines():
        m = re.search(r"corpus/[\w-]+/(\S+\.txt)", line)
        if m:
            names.add(m.group(1))
    return names

def prose_only(text):
    """마크다운 구조 조각(제목·목록·인용 표지·표·코드 줄)을 빼고 산문 줄만 남긴다.
    구조 조각을 문장으로 세면 쉼표 중앙값과 명사형 비율이 왜곡된다."""
    keep = []
    for line in text.splitlines():
        s = line.strip()
        if not s:
            keep.append("")
            continue
        if re.match(r"^(#{1,6}\s|>\s?|[-*+]\s|\d+[.)]\s|\||```|---+$|\[.*\]\(.*\)$)", s):
            continue
        if len(s) < 10 and not re.search(r"[.!?다요죠지]$", s):
            continue
        keep.append(s)
    return "\n".join(keep)

def analyze_genre(kiwi, genre_dir, holdout):
    texts, used, skipped = [], [], []
    for fp in sorted(genre_dir.glob("*.txt")):
        if fp.name in holdout:
            skipped.append(fp.name)
            continue
        t = prose_only(fp.read_text(encoding="utf-8", errors="replace").strip())
        if t:
            texts.append(t)
            used.append(fp.name)
    if not texts:
        return None
    full = "\n\n".join(texts)

    sent_lens, commas, ef_counter, register = [], [], Counter(), Counter()
    no_final_punct = 0
    n_sent = 0
    for text in texts:
        for sent in kiwi.split_into_sents(text):
            s = sent.text.strip()
            if not s:
                continue
            n_sent += 1
            sent_lens.append(len(s))
            commas.append(s.count(",") + s.count("、"))
            if not re.search(r"[.!?…]$|다$|요$|죠$|지$", s):
                no_final_punct += 1
            toks = kiwi.tokenize(s)
            efs = [t for t in toks if t.tag == "EF"]
            if efs:
                form = efs[-1].form
                ef_counter[form] += 1
                if HAPSYO.search(form) or form in ("ᆸ니다", "습니다"):
                    register["합쇼체"] += 1
                elif HAEYO.search(form) or form.endswith("요"):
                    register["해요체"] += 1
                else:
                    register["해체/반말/평서"] += 1
            else:
                register["종결어미 없음(명사형 등)"] += 1

    probes_zero = [p for p in AI_TELL_PROBES if p not in full]
    probes_used = {p: full.count(p) for p in AI_TELL_PROBES if p in full}

    return {
        "files_used": used,
        "files_held_out": skipped,
        "n_docs": len(texts),
        "n_sents": n_sent,
        "n_chars": len(full),
        "sent_len": {
            "mean": round(statistics.mean(sent_lens), 1),
            "median": statistics.median(sent_lens),
            "p90": sorted(sent_lens)[int(len(sent_lens) * 0.9) - 1] if len(sent_lens) >= 10 else None,
        },
        "comma_per_sent": {
            "mean": round(statistics.mean(commas), 2),
            "median": statistics.median(commas),
        },
        "no_final_punct_ratio": round(no_final_punct / n_sent, 3) if n_sent else None,
        "register_ratio": {k: round(v / n_sent, 3) for k, v in register.most_common()},
        "top_endings": ef_counter.most_common(15),
        "never_use_candidates": probes_zero,
        "probes_found": probes_used,
    }

def main():
    if not CORPUS.exists():
        sys.exit(f"코퍼스가 없다: {CORPUS} — 먼저 intake 로 직접 쓴 글을 넣을 것.")
    kiwi = Kiwi()
    holdout = load_holdout()
    OUT.mkdir(parents=True, exist_ok=True)
    summary = ["<!-- GENERATED by scripts/build-fingerprint.py — 손 편집 금지, 재생성만 -->",
               "# fingerprint summary", ""]
    for genre_dir in sorted(CORPUS.iterdir()):
        if not genre_dir.is_dir():
            continue
        r = analyze_genre(kiwi, genre_dir, holdout)
        if r is None:
            summary.append(f"## {genre_dir.name}\n- (비어 있음)\n")
            continue
        (OUT / f"{genre_dir.name}.json").write_text(
            json.dumps(r, ensure_ascii=False, indent=2), encoding="utf-8")
        summary.append(f"## {genre_dir.name}")
        summary.append(f"- 문서 {r['n_docs']}편, 문장 {r['n_sents']}개, {r['n_chars']:,}자 (holdout 제외 {len(r['files_held_out'])}편)")
        summary.append(f"- 문장 길이 중앙값 {r['sent_len']['median']}자, 쉼표 중앙값 {r['comma_per_sent']['median']}개/문장")
        summary.append(f"- 화계: {r['register_ratio']}")
        summary.append(f"- 상위 종결어미: {[e[0] for e in r['top_endings'][:6]]}")
        summary.append(f"- never-use 후보 {len(r['never_use_candidates'])}개 / 탐침 중 실사용 {list(r['probes_found'].keys())[:5]}")
        summary.append("")
    (OUT / "summary.md").write_text("\n".join(summary), encoding="utf-8")
    print("fingerprint 산출 완료 ->", OUT)

if __name__ == "__main__":
    sys.exit(main())
