# native-output — holdout 봉인 선정 (결정론적: 장르별 파일명 정렬 후 7편마다 1편, 약 14%)
# 무작위가 아니라 결정론이어야 재실행해도 같은 봉인이 유지된다.
# 실행: PYTHONIOENCODING=utf-8 python scripts/select-holdout.py
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"
CORPUS = DATA / "corpus"
OUT = DATA / "holdout.md"

def main():
    if OUT.exists():
        print("이미 존재:", OUT, "- 봉인은 갱신하지 않는다 (추가 편입분만 수동 검토). 강제 재선정은 파일 삭제 후 재실행.")
        return 0
    if not CORPUS.exists():
        sys.exit(f"코퍼스가 없다: {CORPUS} — 먼저 intake 로 직접 쓴 글을 넣을 것.")
    lines = ["<!-- GENERATED by scripts/select-holdout.py — 봉인 목록. 팩 제작에 사용 금지 -->",
             "# holdout (평가 전용 봉인)", ""]
    total, held = 0, 0
    for genre_dir in sorted(CORPUS.iterdir()):
        if not genre_dir.is_dir():
            continue
        files = sorted(genre_dir.glob("*.txt"))
        total += len(files)
        picks = [f for i, f in enumerate(files) if i % 7 == 3]
        held += len(picks)
        for f in picks:
            lines.append(f"- corpus/{genre_dir.name}/{f.name}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"봉인 {held}/{total}편 -> {OUT}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
